dist: bionic
sudo: required
language: php
php:
    - '8.0'
    - '7.4'
    - '7.3'
    - '7.2'
    - '7.1'
    - '7.0'
os: linux
before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/bionic-media; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
    - ffmpeg -hwaccels
    - travis_retry composer self-update
    - travis_retry composer update

script:
    - vendor/bin/phpunit
